<Project>
  <!-- Define your Vintage Story game path as VINTAGE_STORY in ./Directory.Build.prop.user
  or via environment variables
   -->
  <Import Condition="Exists('./Directory.Build.prop.user')"
    Project="./Directory.Build.prop.user" />
  <PropertyGroup>
    <VINTAGE_STORY>$(VINTAGE_STORY)</VINTAGE_STORY>
    <VINTAGE_STORY>$(VINTAGE_STORY.Trim())</VINTAGE_STORY>
  </PropertyGroup>
</Project>